### ISSUE TITLE
Error on rotated file if new file takes time to appear

### ISSUE THREAD

**Issue by martinj** [logdna/tail-file-node#18]
If the file is rotated and it takes a while for the new file to appear it will fail.

The first error `ENOENT` will be caught and `_readRemainderFromFileHandle` will be executed, this will set `this[kFileHandle] = null` and on the next succeding poll it will detect a file rename and call `_readRemainderFromFileHandle` again but `this[kFileHandle]` is now null.

Example 

```javascript
'use strict'

const TailFile = require('@logdna/tail-file');
const fs = require('fs');

async function go() {
	const tail = new TailFile('./foo.log');
	tail.on('retry', () => console.log('retry'));
	tail.on('error', console.log)

	await tail.start();

	setTimeout(() => {
		fs.renameSync('./foo.log', './foo.log.1');
	}, 1000);

	setTimeout(() => {
		fs.copyFileSync('./data.txt', './foo.log');
	}, 2100);

}

go().catch(console.log);
```

Output

```
retry
TypeError: Cannot read property 'stat' of null
    at TailFile._readRemainderFromFileHandle (/node_modules/@logdna/tail-file/lib/tail-file.js:123:43)
    at TailFile._pollFileForChanges (/node_modules/@logdna/tail-file/lib/tail-file.js:171:20)
```

**Comment by darinspivey** [comment]
Ah, right you are!  Thank you for reporting this, and for providing a working example.  Looks like this edge case was just missed.  There are 2 places that will read 'the remainder' from the FH; one for when the inode changes and one for if the file disappears.  The former condition can happen if the file changes in between polls, thus never throwing an `ENOENT` error.  This edge case is sort of a combination of the two and should definitely be handled.  After all, the code is designed to be configurable for wait time and number of retries after a file disappears.

I've completed the coding fix, but need to update the tests.  This can be merged asap after the US is back from the holiday weekend in a few days.  Thanks again.
