### ISSUE TITLE
`TailFile` modifies the log file encoding

### ISSUE THREAD

**Issue by tukusejssirs** [logdna/tail-file-node#20]
I use `TailFile` to watch the tail changes of Windows files on Linux server with `\r` line endings, however, after I run the `TailFile` over that file, the encoding (reported by `file`) changes from `ISO-8859 text, with CR line terminators` to `UTF-8 Unicode text` with `\n` endings.

Of course, I used `new TailFile(file, {encoding: 'utf8'})` (i.e. `utf8` encoding), however, `cp1250` nor `win1250` is a supported encoding (yes, I know, `file` reports it as `ISO-8859`, but it is not 100 % percent same). I would like to pre-parse it using `iconv-lite`, but I am not sure if it is possible using the current `tail-file-node` implementation.

The only workaround I see is to change the encoding of the original file to `utf8` and change the line endings to `\n`, but saving it to a different location (i.e. preserve the original file encoding and line endings) and then watch the new file instead of the original one.

That said I think that the file should be open read-only, i.e. no change should be made to its content including encoding and line ending.

**Comment by darinspivey** [comment]
Some things need clarified here.  `tail-file` shouldn't care much about the encoding of `\r` characters since it's a passthrough and doesn't re-write any data.  Are you saying that the `data` event no longer contains`\r` characters when `tail-file` emits that event?

**Comment by tukusejssirs** [comment]
> `tail-file` shouldn't care much about the encoding of `\r` characters

You are right, `tail-file` does not care about the line endings, but it does change than to `\n` and also the encoding to `utf8` (as `file` and Sublime Text report it)

> Are you saying that the `data` event no longer contains`\r` characters when `tail-file` emits that event?

Yes, there is no `\r` and they are replaced by `\n` + the encoding change right after starting the monitoring.

---

Just to be clear: this is issue is less important to us than #19 and #21, because we copy files from a remote computer and therefore we could modify the encoding and line endings just before the the data is copied to the server-side location. That said, I still regard it as a bug.

[R2021Mar23.txt](https://github.com/logdna/tail-file-node/files/6580172/R2021Mar23.txt) is an example log I need to process. I had to change the file extention from `REP` to `txt` in order make GitHub happy. :wink:

**Comment by darinspivey** [comment]
Question: are you using some of the examples which use `readline` to consume `data` lines?

**Comment by tukusejssirs** [comment]
No, I use a coded upon the [`pipe`](https://github.com/logdna/tail-file-node#example-using-pipe) example incl. `split2`.

**Comment by darinspivey** [comment]
> after I run the TailFile over that file, the encoding (reported by file) changes from ISO-8859 text, with CR line terminators to UTF-8 Unicode text with \n endings.

Hmm, ok.  I got your log file, thanks.  Can you provide some working example code that duplicates the problem using that log file?  That way we're debugging based on the same test case.  We're having a hard time understanding your issue because `tail-file` doesn't modify the data.  Even when using something like `split2`, it will split lines on `\n` OR `\r\m`, and thus the `data` event won't have any carriage returns in it.  I don't follow the "before" and "after" context for when you saying that the encoding changes.  It seems like if anything is changing, that's outside the scope of `tail-file`, no?

**Comment by tukusejssirs** [comment]
You’re right. `tail-file` does not modify the file content, but my text editor. :facepalm:

Explanation: in order to test `tail-file` locally on my computer, I edited the file which running `tail-file` as if it was appended by the client computer. The thing is that I have my text editor configure to use `\n` newlines and `utf8`, so it converted the file line endings and newlines.

Sorry for opening a non-existent issue.
