### ISSUE TITLE
Is it possible to watch log files with date in the filename?

### ISSUE THREAD

**Issue by tukusejssirs** [logdna/tail-file-node#21]
I need to watch files with date in the filename. These files are appended with data until midnight every day, after which a new file with a new date is created.

As far as I see it, currently there is no way to deal with such logs within `tail-file-node`. Could you add support for such logs please? :wink:

**Comment by darinspivey** [comment]
It shouldn't care what the filename is.  I think you're asking if `tail-file` can somehow know the name of the new file (containing a new datestamp) and resume tailing from the new filename automatically?

**Comment by tukusejssirs** [comment]
> I think you're asking if `tail-file` can somehow know the name of the new file (containing a new datestamp) and resume tailing from the new filename automatically?

Yes, exactly. However, I don’t think it should do so by default, but when a `tail-file` option is set (for example) to the filename format (e.g. `YYYYMMDD.ext`; `tail-file` would only replace the date part, the rest it would use literally).

Just as an example: one of our files to use is namd `R2021Jun01.REP`. Don’t tell me how strange it is, but on the particular machine, there are even more strange things than this is. :thinking: :wink:

**Comment by darinspivey** [comment]
I see.  It's an interesting proposal but would add some complexity to the code.  Is there no way to know what the new file is, and `.quit()` the old tailer while restarting a new one with the new filename?  I worry that file globs and things add unnecessary complexity when it could just be restarted as a simple solution.  The polling timers make doing filename updates on-the-fly dangerous and racey.

**Comment by tukusejssirs** [comment]
I see.

Actually, the filename is always the same, only the date part changes according to today, so yescould simply use `.quit()`. Thanks!

**Comment by darinspivey** [comment]
Good deal.  Closing out.
