### ISSUE TITLE
Is it possible to change the buffer size?

### ISSUE THREAD

**Issue by seed-of-apricot** [logdna/tail-file-node#39]
I want to keep watching a log file where one line could be ~100KB and it seems the first 65536 bytes are read now.
Is is possible to change the maximum buffer size?

**Comment by darinspivey** [comment]
It sounds like you're wanting to change the `highWaterMark` for the read stream?  Based on your short description, it's hard to tell what is or is not happening.  The high water mark is a backpressure mechanism for node internals, so it should still output a line that's 100KB.  You shouldn't have to tweak that based on your line size, but I might be missing something.

In any case, if you want to try and change that, the [readStreamOpts](https://github.com/logdna/tail-file-node#constructor-new-tailfilefilename-options) can be set to use a different [high water mark](https://nodejs.org/docs/latest-v18.x/api/fs.html#filehandlecreatereadstreamoptions).

**Comment by seed-of-apricot** [comment]
I have changed my code after making this issue and now each of my lines is shorter than 65536 bytes, but basically, it was something like this:

```ts
const tail = new TailFile(path, {
  encoding: "utf8",
  pollFileIntervalMs: 100,
});

tail
  .on("data", async (data) => {
    console.log(data.length); // 65536 even when a line contains more
  })
  .start();
```

But thank you for your suggestion. If there is any need for the option in the future I will set it.
